require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/DescribedClass:
  EnforcedStyle: explicit

Layout/LineLength:
  Max: 120
